# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - reviewsentiments

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to container registry
        uses: docker/login-action@v2
        with:
          registry: dockerimagestreamlit.azurecr.io/
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A82C5B74F38140CC8668B4F69CBF1E58 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_2F35C392D8E64B47BF48EE475D145BE9 }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: dockerimagestreamlit.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A82C5B74F38140CC8668B4F69CBF1E58 }}/amazonreviewsentiment:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    needs: build
    

    steps:
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2DA8F9E44E0744D1A7AD5B42DD851576 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C6AAC8B2B0D441D0B1CB15AF52D19351 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_5FB120F8FAAB4E2181833B998BABBDEE }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'reviewsentiments'
          slot-name: 'Production'
          images: 'dockerimagestreamlit.azurecr.io/${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_A82C5B74F38140CC8668B4F69CBF1E58 }}/amazonreviewsentiment:${{ github.sha }}'
          